name: arm_project

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.4.3
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_analytics: ^10.1.4
  firebase_core: ^2.7.0
  firebase_database: ^10.0.14
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.1
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.1
  get_time_ago: ^1.2.2
  intl: ^0.18.0
  syncfusion_flutter_charts: ^20.4.51
  syncfusion_flutter_gauges: ^20.4.51

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/electrical-energy.png
    - assets/images/microchip.png
    - assets/images/notification.svg
    - assets/images/generator.png
    - assets/images/fuel.png
    - assets/images/yellow_led.png
    - assets/images/white_led.png

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Manrope-Bold.otf
          weight: 700
        - asset: assets/fonts/Manrope-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Manrope-Medium.otf
          weight: 500
        - asset: assets/fonts/Manrope-Regular.otf
          weight: 400
        - asset: assets/fonts/Manrope-Light.otf
          weight: 300
        - asset: assets/fonts/Manrope-ExtraLight.otf
          weight: 200
